import nft1 from "../images/nft1.jfif";
import nft2 from "../images/nft2.jfif";
import nft3 from "../images/nft3.jfif";
import nft4 from "../images/nft4.jfif";
import nft5 from "../images/nft5.jfif";
import nft6 from "../images/nft6.jfif";
import nft7 from "../images/nft7.jfif";
import nft8 from "../images/nft8.jfif";
import nft9 from "../images/nft9.jfif";
import nft10 from "../images/nft10.jfif";

export const nfts = [
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 1,
    name: nft1,
    bgcolor: "bg-[#a19e99]",
    serialno: 243,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 2,
    name: nft2,
    bgcolor: "bg-[#46436e]",
    serialno: 453,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 3,
    name: nft3,
    bgcolor: "bg-[#c62f42]",
    serialno: 763,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 4,
    name: nft4,
    bgcolor: "bg-blue-500",
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 5,
    name: nft5,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 6,
    name: nft6,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 7,
    name: nft7,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 8,
    name: nft8,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 9,
    name: nft9,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 10,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 11,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 12,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 13,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 14,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
  {
    title: "AZUKI",
    price: "NO.5000",
    id: 15,
    name: nft10,
    obj: {
      type: "HUMAN",
      clothing: "RED HOODIE",
      hair: "MAGENTA LONG",
      mouth: "GAITER",
      offhand: "WATER ORB",
      eyes: "MEDITATING",
      background: "OFF WHITE D",
    },
  },
];
